version: '2'
services:
  web:
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
    - 3000:3000
    volumes:
    - .:/code
    links:
    - mysql
  mysql:
    image: mysql:5.6
volumes:
  logvolume01: {}
